### PR TITLE
add some installation pod and move 99-* tests to xt directory

### PR DESCRIPTION
**Pull request by lharey**
Hi

As per our emails about the Pull Request challenge.

I have tested the ubuntu installation of phantomjs and added the details to pod.

I have moved the 99-* tests to xt directory and also added a new test xt/99-compile.t

Hope this is what you require.

Regards
Lisa

### CODE REVIEW

**Comment by Corion** [comment]
Hello Lisa,

thank you very much! This is far more than I expected and I'm really 
thankful for the great work you've done integrating the parts!

Thanks for participating in the Pull Request Challenge!

-max

Am 15.04.2016 um 17:30 schrieb Lisa Hare:

**Comment by dk** [comment]
Hi Max,

I'd very much like to ask you to look at https://github.com/Corion/www-mechanize-phantomjs/pull/13 ang give your feedback. You're not merging it so far and that's okay, you have youre reasons, but I'd like to hear if there's anything wrong with my patches

Thank you
Dmitry

**Comment by Corion** [comment]
Hi Dimitry,

those are next on my list :)

I'm not too fond of adding the ->find_css and ->find_xpath (because 
there already is ->selector, I think), but the others will likely be 
merged soonish as well. The CPAN Pull Request Challenge was what 
prompted me to revisit the patches.

Thanks for the patches
-max

Am 16.04.2016 um 10:10 schrieb Dmitry Karasik:

**Comment by dk** [comment]
That's all right! Good to know :)

**Pull request merged**
